create table contacts (
    id bigint generated by default as identity,
    name varchar(255),
    uuid  varchar(255),
    sex varchar(255),
    position varchar(255),
    age varchar(255),
    photo varchar(255),
    desc varchar(255),
    primary key (id)
);
